# Generated by Django 4.2.5 on 2023-09-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='title',
        ),
    ]
